import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

import Link from "next/link";
export default function Home() {
  const gethanel = () => {
    <Link>
      <a href="/user"></a>
    </Link>;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h2>The Frist Page Next Run </h2>
          <Link href="/users">
            <button
              onClick={gethanel}
              style={{ padding: "30px", color: "red", outline: "none" }}
            >
              User
            </button>
          </Link>
          <Link href="/posts">
            <button
              onClick={gethanel}
              style={{ padding: "30px", color: "red", outline: "none" }}
            >
              Post
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
